name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    # To enable auto publishing to github, update your electron publisher
    # config in package.json > "build" and remove the conditional below

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3

      - name: Install Node and NPM
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      # Step to clone the sourly-webcore repo
      - name: Clone sourly-webcore
        run: |
          git clone https://github.com/sour-ly/sourly-webcore.git ../sourly-webcore



      - name: Install and build
        run: |
          cd ../sourly-webcore
          npm install
          cd ../sourly-electron
          npm install
          npm run postinstall
          npm link ../sourly-webcore
          npm run build

      - name: Publish releases
        env:
          # The APPLE_* values are used for auto updates signing
          # APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASS }}
          # APPLE_ID: ${{ secrets.APPLE_ID }}
          # APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # CSC_LINK: ${{ secrets.CSC_LINK }}
          # CSC_KEY_PASSWORD: ${{ secrets.CSC_KEY_PASSWORD }}
          # This is used for uploading release assets to github
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm exec electron-builder -- --publish always --win --linux --mac --x64 --arm64
